language: python
python:
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install --user codecov
# command to run tests
script: python3 Main.py
after_success:
  - codecov
